# Generated by Django 6.0.4 on 2026-04-21 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('short_description', models.TextField(help_text='Enter a short description that would fit on the events display.', max_length=200)),
                ('long_description', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=50, unique=True)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
