# Generated by Django 6.0.4 on 2026-04-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-title'], 'permissions': (('can_create_event', 'Create an Event'), ('can_edit_event', 'Edit an Event'), ('can_delete_event', 'Delete an Event'))},
        ),
    ]
