services:
  - type: web
    plan: free
    name: theboard
    runtime: python
    buildCommand: '/build.sh'
    startCommand: 'python -m gunicorn theboard.asgi:application -k uvicorn.workers.UvicornWorker'